---
version: '2'

linters:
  default: all
  disable:
    - depguard # We don't use dep
    - exhaustruct # mutexes don't require exhaustive structs
    - tagliatelle # We don't need opinions on struct tags
    - noinlineerr # We don't need opinions on error handling'
    - wsl # legacy
    - cyclop # Already present in revive
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    revive:
      enable-all-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: line-length-limit
          arguments: [ 120 ]
        - name: confusing-results
          disabled: true # it conflicts with nonamedreturns
        - name: add-constant
          disabled: true
        - name: function-length
          arguments:
            - 50
            - 100
        - name: cognitive-complexity
          arguments: [ 20 ]
        - name: cyclomatic
          arguments: [ 15 ]
    mnd:
      ignored-numbers: [ 0,1,2,3 ] # These are often used as defaults, not magic numbers
    funlen:
      lines: 120

formatters:
  enable:
    - gci
    - gofmt
