package ui_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hyperized/uAirwaves/internal/ui"
	"github.com/hyperized/uAirwaves/pkg/coverage"
	"github.com/rivo/tview"
)

const (
	coveragePanelWidth  = 46
	coveragePanelHeight = 12

	// Seeded-fixture parameters. seededCountStep scales the per-cell count
	// so the seeded cone sweeps through every density glyph; the two range
	// values drive the caption.
	seededCountStep     = 9
	seededMaxRangeNm    = 152
	seededMaxRangeAltFt = 38000
)

// seededCoverageCone builds a deterministic cone whose reception reach
// widens with altitude (high aircraft are seen farther) and whose counts
// fall with range, so the rendered glyphs sweep from full blocks near the
// receiver to empty-cell dots at the edges. It is the exact input the
// golden fixture was generated from — regenerate the fixture by feeding
// this snapshot back through FormatCoverageCone.
func seededCoverageCone() coverage.Snapshot {
	var snap coverage.Snapshot

	reach := [coverage.AltitudeBandCount]int{2, 4, 7, 10, 13, 16, 19, 22, 24, 25}
	for band := range coverage.AltitudeBandCount {
		for bin := range reach[band] {
			//nolint:gosec // (reach-bin)*step is a small positive product; no uint32 overflow.
			snap.Cells[band][bin] = uint32((reach[band] - bin) * seededCountStep)
		}
	}

	snap.MaxRangeNm = seededMaxRangeNm
	snap.MaxRangeAltFt = seededMaxRangeAltFt

	return snap
}

// seededCoverageShadows builds a silhouette with a hard null: bearing
// sectors 6 and 7 (the SE quadrant) carry zero range, so the plot renders
// a missing wedge — the antenna shadow the view is meant to surface.
func seededCoverageShadows() coverage.Snapshot {
	var snap coverage.Snapshot

	snap.Sectors = [coverage.BearingSectorCount]float64{
		140, 150, 120, 100, 80, 60, 0, 0, 90, 110, 130, 120, 100, 70, 60, 90,
	}
	snap.MaxRangeNm = seededMaxRangeNm
	snap.MaxRangeAltFt = seededMaxRangeAltFt

	return snap
}

// readGolden loads a byte-exact fixture from testdata. Fixtures are
// regenerated by writing the corresponding Format* output back to the file.
func readGolden(t *testing.T, name string) string {
	t.Helper()

	//nolint:gosec // test-only golden fixture; name is a compile-time literal from this file.
	body, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("read golden %s: %v", name, err)
	}

	return string(body)
}

// TestFormatCoverageConeEmpty pins the empty-tracker cone: every cell is
// the empty glyph, the four altitude labels sit on their rows, the ruler
// anchors 0/100/200 nm, and the caption shows the no-data dash.
func TestFormatCoverageConeEmpty(t *testing.T) {
	t.Parallel()

	got := ui.FormatCoverageCone(coverage.Snapshot{}, coveragePanelWidth, coveragePanelHeight)
	if want := readGolden(t, "coverage_cone_empty.golden"); got != want {
		t.Errorf("cone (empty) mismatch\ngot:\n%s\n\nwant:\n%s", got, want)
	}
}

// TestFormatCoverageConeSeeded pins the seeded cone: the density glyphs
// step from full block near the receiver down to the empty dot at the
// edges, widening with altitude, and the caption reports the peak range.
func TestFormatCoverageConeSeeded(t *testing.T) {
	t.Parallel()

	got := ui.FormatCoverageCone(seededCoverageCone(), coveragePanelWidth, coveragePanelHeight)
	if want := readGolden(t, "coverage_cone_seeded.golden"); got != want {
		t.Errorf("cone (seeded) mismatch\ngot:\n%s\n\nwant:\n%s", got, want)
	}
}

// TestFormatCoverageShadowsEmpty pins the empty-tracker silhouette: the
// receiver crosshair at centre, the four cardinals, no fill, and the
// no-coverage caption.
func TestFormatCoverageShadowsEmpty(t *testing.T) {
	t.Parallel()

	got := ui.FormatCoverageShadows(coverage.Snapshot{}, coveragePanelWidth, coveragePanelHeight)
	if want := readGolden(t, "coverage_shadows_empty.golden"); got != want {
		t.Errorf("shadows (empty) mismatch\ngot:\n%s\n\nwant:\n%s", got, want)
	}
}

// TestFormatCoverageShadowsSeeded pins the seeded silhouette: a filled
// pattern with the SE wedge (sectors 6 and 7) cut away, and the edge-scale
// caption.
func TestFormatCoverageShadowsSeeded(t *testing.T) {
	t.Parallel()

	got := ui.FormatCoverageShadows(seededCoverageShadows(), coveragePanelWidth, coveragePanelHeight)
	if want := readGolden(t, "coverage_shadows_seeded.golden"); got != want {
		t.Errorf("shadows (seeded) mismatch\ngot:\n%s\n\nwant:\n%s", got, want)
	}
}

// TestFormatCoverageConeTinyPanel drives the clamp paths: a width below the
// label gutter yields zero distance columns, and a height below the row
// count truncates to the top altitude bands.
func TestFormatCoverageConeTinyPanel(t *testing.T) {
	t.Parallel()

	const (
		tinyWidth  = 2
		tinyHeight = 4
	)

	got := ui.FormatCoverageCone(seededCoverageCone(), tinyWidth, tinyHeight)
	if want := "    \n40k \n    \n30k "; got != want {
		t.Errorf("cone (tiny) = %q, want %q", got, want)
	}
}

// TestFormatCoverageShadowsTinyPanel drives the clamp and out-of-grid
// cardinal paths: a two-row plot drops the South label off the bottom edge.
func TestFormatCoverageShadowsTinyPanel(t *testing.T) {
	t.Parallel()

	const (
		tinyWidth  = 5
		tinyHeight = 3
	)

	got := ui.FormatCoverageShadows(seededCoverageShadows(), tinyWidth, tinyHeight)
	if want := "  N  \nW▓+▓E\n" + ui.DimTag + "edge 150 nm" + ui.ResetTag; got != want {
		t.Errorf("shadows (tiny) = %q, want %q", got, want)
	}
}

// TestCoverageViewCycle pins the mode cycle cone -> shadows -> off -> cone
// and the cone default.
func TestCoverageViewCycle(t *testing.T) {
	t.Parallel()

	view := ui.NewCoverageView()
	if got := view.Mode(); got != ui.CoverageCone {
		t.Fatalf("new view mode = %v, want cone", got)
	}

	for _, want := range []ui.CoverageMode{ui.CoverageShadows, ui.CoverageOff, ui.CoverageCone} {
		view.Cycle()

		if got := view.Mode(); got != want {
			t.Errorf("after Cycle mode = %v, want %v", got, want)
		}
	}
}

// TestCoverageModeString pins the footer-chip label for every mode plus the
// out-of-range fallback.
func TestCoverageModeString(t *testing.T) {
	t.Parallel()

	for _, testCase := range []struct {
		name string
		mode ui.CoverageMode
		want string
	}{
		{"cone", ui.CoverageCone, "cone"},
		{"shadows", ui.CoverageShadows, "shadows"},
		{"off", ui.CoverageOff, "off"},
		{"unknown", ui.CoverageMode(9), "?"},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			if got := testCase.mode.String(); got != testCase.want {
				t.Errorf("String() = %q, want %q", got, testCase.want)
			}
		})
	}
}

// TestUpdateCoveragePanelPerMode confirms the side-effecting panel setter
// dispatches to the right formatter for each mode and clears the panel when
// off.
func TestUpdateCoveragePanelPerMode(t *testing.T) {
	t.Parallel()

	for _, testCase := range []struct {
		name string
		mode ui.CoverageMode
		want string
	}{
		{"cone renders the caption", ui.CoverageCone, "max — nm"},
		{"shadows renders the placeholder", ui.CoverageShadows, "no coverage yet"},
		{"off clears the panel", ui.CoverageOff, ""},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			panel := tview.NewTextView()
			ui.UpdateCoveragePanel(panel, testCase.mode, coverage.Snapshot{})

			got := panel.GetText(true)
			if testCase.want == "" {
				if got != "" {
					t.Errorf("panel text = %q, want empty", got)
				}

				return
			}

			if !strings.Contains(got, testCase.want) {
				t.Errorf("panel text = %q, want substring %q", got, testCase.want)
			}
		})
	}
}
